### ISSUE TITLE
Request for a working example. 

### ISSUE THREAD

**Issue by rlam3** [AndrewSB/Expirable#1]
Request for a working example. Thanks!

**Comment by AndrewSB** [comment]
Hey @rlam3! Is the tiny example in the README enough, or are you looking for something larger? I could throw together a quick playground if that is the case 😄

**Comment by rlam3** [comment]
Hey @AndrewSB Definitely a larger project a long with moya/moya. I'm at the point where I need to understand how to deal the state of the user's authentication per request. Trying to make sure everytime a request is sent out that the token isn't expired.

**Comment by rlam3** [comment]
@AndrewSB I'd really like a demo of this. Unless there are new changes which don't allow for this when using the AuthPlugin https://github.com/Moya/Moya/blob/master/docs/Examples/AuthPlugin.md Thanks!

**Comment by rlam3** [comment]
I'm also trying to get Cely to work with Expirable, but it seems that subclassing the protocol into the CelyUser class isn't the best way for rxswift to work well.. Would love your thoughts on this matter. Thanks! @AndrewSB 

https://github.com/chaione/Cely/issues/24

**Comment by AndrewSB** [comment]
Hey, I made a working demo in Example.playground, give it a whirl and let me know if you need anything else!
